Repository openshift-assisted/assisted-grafana, pull requests merged in 2025-08, with the labels that each got.

#20 Don't require root path in assisted chat metrics
  dashboards/assisted-chat/grafana-dashboard-assisted-chat-overview.yaml
Labels: approved, size/XS, lgtm

#24 Assisted Chat: Change sizes of charts
  dashboards/assisted-chat/grafana-dashboard-assisted-chat-overview.yaml
Labels: size/M, approved, lgtm, needs-ok-to-test

#25 Assisted Chat: Add cpu/memory charts to overview
  dashboards/assisted-chat/grafana-dashboard-assisted-chat-overview.yaml
Labels: approved, size/XL, lgtm, ok-to-test
