Repository openshift-assisted/assisted-grafana, pull requests merged in 2025-07, with the labels that each got.

#13 add assisted-chat overview dashboard
  dashboards/assisted-chat/grafana-dashboard-assisted-chat-overview.yaml
Labels: size/L, approved, lgtm

#14 add approvers to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, size/XS

#16 NO-ISSUE: Update RDS datasource
  dashboards/assisted-service/grafana-dashboard-assisted-rds-postgres.configmap.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#19 assisted-chat metrics
  dashboards/assisted-chat/grafana-dashboard-assisted-chat-overview.yaml
Labels: size/L, approved, lgtm
